version: "3.1"

services:
  db:
    image: mysql:8
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "dbUser"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "twitter"
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - 3306:3306
